#!/usr/bin/env bash
#display numbers 1-100
#displays the word fizzbuzz if multiple of 3 and 5
#displays fizz when the number is a multiple of 3
#displays buzz when the number is a multiple of 5

for i in {1..100}
do
	if [ $((i % 3 == 0 ] && [ $((i % 5)) == 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 3)) == 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) == 0 ]
	then
		echo "Buzz"
	else
		echo $i
	fi
done
