#!/usr/bin/env bash
#displays contents of a file '/etc/passwd'.
#only displays username user id, and home directory for the user

file=/etc/passwd

while read -r line; do
	echo "$line" | cut -f 1,3,6 -d ':'
done < "$file"
