#!/usr/bin/env bash
#displays contents of a file '/etc/passwd'.
#only displays username user id, and home directory for the user

while read   passwd; do
	echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
