#!/usr/bin/env bash
#displays the contents of /etc/passwd, using the while loop IFS.

while IFS=':' read username password uid gid info home shell; do
	echo "The user $username is part of the $gid gang,"\
	"lives in $home and rides $shell."\
	"$uid's place is protected by the passcode $password,"\
	"more info about the user here: $info"
done < "/etc/passwd"
