#!/usr/bin/env bash
#displaying Best School 10 times in 9th say hi.

x=1
while [ $x -le 10 ]
do
	if [ $x -eq 9]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
x=$((x + 1))
done
