#!/usr/bin/env bash
#displays numbers 1-20

#displays 4 and then bad luck from China for the 4 loop
#displays 9 and then bad luck from Japan for hte 9 loop
#displays 17 and then bad luck from Italy for the 17 loop

count=1

while [ $count -le 20 ]
do
	echo "$count"
	case $count in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( count++ ))
done
