#!/usr/bin/env bash
#writing Bash script displays

#the content of the current directory
#In a list form
#where only part of the name after the first dash is displayed

list=$(ls)
for i in $list; do
	echo "$i" | cut -d '-' -f2
done
