#!/usr/bin/env bash
#To infinity and beyond indefinitely, With sleep 2 between each iteration,I am invincible!!! when receiving a SIGTERM signal

for (( i=1; i>0; i++ ))
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
